version: "2"

services:
    postgres:
        image: postgres:9.6
        ports:
            - 5435:5432
        hostname: postgres-it
        environment:
            POSTGRES_USER: demo
            POSTGRES_PASSWORD: demopw
            POSTGRES_DB: demodb
        volumes:
            - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
